import * as T from 'three';
// HHMI Janelia FlyEM MaleCNS v1.0; MRC LMB Cambridge and Cambridge Zoology;
// Google Research. FlyWire Consortium and Princeton Murthy/Seung Labs: explorer credits.
// Original anatomy remains CC-BY-4.0; activity overlays are generated by our LIF model.
export class Anatomy {
  group=new T.Group();private materials:T.ShaderMaterial[]=[];private lastPulse=-10;
  async load(){
    const manifest=await (await fetch('/data/anatomy.json')).json();
    const regionGroup=new T.Group(),neurons=new T.Group();
    for(const region of manifest.regions){
      for(const file of region.fragments){
        const response=await fetch('/data/'+file+'.edges');if(!response.ok)throw new Error('Missing prepared anatomy');
        const positions=new Float32Array(await response.arrayBuffer());
        const g=new T.BufferGeometry();g.setAttribute('position',new T.BufferAttribute(positions,3));
        const edge=new T.LineSegments(g,new T.LineBasicMaterial({color:0x8683c0,transparent:true,opacity:.13,depthWrite:false}));
        regionGroup.add(edge);
      }
    }
    const bounds=new T.Box3().setFromObject(regionGroup),center=bounds.getCenter(new T.Vector3()),size=bounds.getSize(new T.Vector3());
    for(const entry of manifest.skeletons){
      const text=await (await fetch('/data/'+entry.file)).text();const points=new Map<number,T.Vector3>();const rows:number[][]=[];
      for(const line of text.split('\n')){if(!line.trim()||line.startsWith('#'))continue;const v=line.trim().split(/\s+/).map(Number);if(v.length<7||v.some(x=>!Number.isFinite(x)))continue;points.set(v[0]!,new T.Vector3(v[2]!*8,v[3]!*8,v[4]!*8));rows.push(v);}
      const positions:number[]=[],travel:number[]=[];
      for(const row of rows){const p=points.get(row[0]!),parent=points.get(row[6]!);if(!p||!parent)continue;
        // Brain compartment bounds exclude the VNC; the UI focuses on the brain.
        if(!bounds.containsPoint(p)||!bounds.containsPoint(parent))continue;
        positions.push(...p.toArray(),...parent.toArray());travel.push((p.z-bounds.min.z)/size.z,(parent.z-bounds.min.z)/size.z);
      }
      if(!positions.length)continue;
      const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('travel',new T.Float32BufferAttribute(travel,1));
      const material=new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,
        uniforms:{clock:{value:0},fired:{value:-100},tint:{value:new T.Color(entry.label.startsWith('DN')?0x80ffd1:0xa89aff)}},
        vertexShader:'attribute float travel; varying float vTravel; void main(){vTravel=travel;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',
        fragmentShader:'uniform float clock;uniform float fired;uniform vec3 tint;varying float vTravel;void main(){float age=clock-fired;float wave=exp(-pow((vTravel-age*1.7)*16.,2.))*step(0.,age)*step(age,1.);gl_FragColor=vec4(mix(vec3(.25,.35,.48),tint,wave),.25+wave*.75);}'
      });
      this.materials.push(material);neurons.add(new T.LineSegments(g,material));
    }
    regionGroup.position.copy(center).multiplyScalar(-1);neurons.position.copy(center).multiplyScalar(-1);
    this.group.add(regionGroup,neurons);this.group.scale.setScalar(3.2/size.x);this.group.rotation.x=Math.PI/2;
    return {regions:manifest.regions.length,neurons:this.materials.length};
  }
  update(time:number){for(const m of this.materials)m.uniforms.clock!.value=time;}
  spike(time:number,motor=false){if(time-this.lastPulse<.45)return;this.lastPulse=time;for(const m of this.materials){m.uniforms.fired!.value=time;m.uniforms.tint!.value.setHex(motor?0x86ffd0:0xc1a3ff);}}
}
